### ISSUE TITLE
Inkybay doesn't call the hook-address

### ISSUE THREAD

**Issue by BeneReuthlinger** [efoli-llc/inkybay-shopify-order-sdk#1]
Hello,

I've been trying to get the api to work for months, unfortunately it doesn't work.
Meanwhile it worked with the export to google-drive, but unfortunately that doesn't work anymore either.
That's why i tried it again with this sdk.
The main problem is that inkybay does not connect to the hook address.
My Hook-Address: ...

`
	require_once('conf.php');

	$data = $orderService->getOrder('orderId', 'json', array('orderId' => '164736461873'));
	
	file_put_contents('test.txt', "RemoteIP: " . $_SERVER['REMOTE_ADDR'] . "\nTime: " . date('Y-m-d H:i:s') . "\nData: " . $data);
	
	header('Content-type: application/json');
	echo $data;
`

I hope you can help me.
thanks in advance

best regards 
bene

**Comment by efolidev** [comment]
Hello @BeneReuthlinger,

You have to update your code to catch json data as like as below:

`$data = $orderService->getOrder($_GET['orderId'],'json');`

Thanks

**Comment by BeneReuthlinger** [comment]
Hello Efoli,

I think it works now. 
If there are still problems I would report back.

thx for help

**Comment by efoli-llc** [comment]
Everything  running ok
